platform :ios, '13.0'
use_frameworks!

project 'App/App.xcodeproj'

target 'App' do
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end
